version: 2.1
orbs:
   node: circleci/node@5.0.2
jobs:
   build:
      docker:
         - image: node:16
      steps:
         - checkout
         - run:
            name: install packages
            command: yarn install
         - run:
            name: unit tests
            command: yarn test:unit
         - run:
            name: integration tests
            command: yarn test:int
